export default {
	p1:
		"I hereby certify that all information herein are true and correct based on my own personal knowledge. I authorize the Bank to obtain information as it may require concerning my loan application and agree that it shall remain the Bank's property whether my loan is approved or not. Any information given by me or other persons duly authorized by me which is not true or accurate, will automatically cause the Bank to reject my loan, cancel its approval or if the loan has been released to me, to demand immediate payment thereof.",
	p2:
		"I hereby waive my rights and benefits under the provisions of R.A. 9510 (Credit Information System Act), R.A. 1405 (Secrecy of Bank Deposit Act), R.A. 6426 (Foreign Currency Deposits Act), R.A. 8791 (General Banking Law), R.A. 9160 (Anti-Money Laundering Act) and other laws on confidentiality of bank account, credit, loan and other related information and hereby authorize the Bank to process divulge, or make necessary disclosure of such otherwise confidential information, to third parties, including but not limited to the Bank's affiliates, subsidiaries, agents or service providers, the Bankers' Association of the Philippines Credit Bureau (BAP — CB) or to other credit bureau or to any similar central monitoring entity or recipients as may be provided for by law and required by competent authority.",
	p3:
		'I further authorize the Bank, as my Attorney-in-Fact, to conduct random verification with the Bureau of Internal Revenue (the "BIR") in order to establish the authenticity of my tax statements (the "ITR") and the accompanying financial statements/documents submitted to the Bank in accordance with banking regulatory requirements and/or to process, report, share and disclose my information to domestic or foreign authorities and/or tax authorities and/or withhold from me, such amounts as may be required by domestic or foreign regulatory and/or tax authorities in accordance with the requirements of United States Foreign Account Tax Compliance Act (FATCA), and such other rules and regulations issued and/or may be issued, by the Government of the Philippines in connection with FATCA.',
	p4:
		'For this purpose, I hereby authorize the Bank, its employees or its agent to verify and obtain information relevant to my loan application, such as, but not limited to residential and contact information, business or trade and payment performance.',
	p5:
		'I hold the Bank free and harmless from any and all liabilities, claims and demands of whatever kind or nature in connection with or arising from the aforementioned disclosure or reporting.',
	p6:
		"I hereby acknowledge that the loan or any part(s) thereof shall be deemed to have been availed on the date on which funds are transferred to my bank account or cash/prepaid card, maintained with the Bank, or receipt of the Manager's Check reflecting the amount of the loan less applicable fees, charges and taxes.",
	p7:
		'I further authorize the Bank to deduct from the proceeds of my loan, all fees including, but not limited to, processing fees, documentary stamp tax, notarial fees and interest accruals should the first due date be over 30 days from the release of my loan and other related charges.',
	p8:
		"I likewise authorize the Bank to provide me with a consumer loan or additional bank product/s (such as but not limited to auto, housing, credit card and other products suited to my situation) at the Bank's sole discretion. My acceptance of the credit card or the proceeds of any loan released pursuant thereto shall be conclusive proof of my acknowledgment of my additional obligations and/or indebtedness to the Bank under the Terms and Conditions set forth by the Bank and prevailing at the time the credit card is issued or the additional loan is approved.",
	p9:
		'I hereby agree that the Bank has the right to approve a lower amount than my desired loan amount as indicated in this application and shall render the Bank free and harmless from any liability arising thereof.',
	p10:
		'I hereby agree that should my application be denied, the Bank has no obligation to furnish the reason for such rejection or to return my application and other submitted documents.',
	p11:
		'I also legally bind myself to the Terms and Conditions of the Loan Program Promissory Note, Disclosure Statement and other relevant documents that I shall execute in favor of the Bank.',
	p12:
		'I hereby freely and voluntarily give my consent, and hereby agree and authorize the Company, its parent company, affiliated companies, subsidiaries, financial advisors, accredited/affiliated third parties or independent/non-affiliated third parties, whether local or foreign (collectively referred to as Companies), to collect and process matter or information, personal or otherwise, pertaining to myself, this application or transaction, including sensitive personal information and privileged information (as defined under existing laws and subject to consent of other parties to the exchange as may be applicable) herein provided, collected or held or otherwise obtained separately by the Companies, and to disclose the above information between and among the Companies, for any legitimate business purpose as such Companies may deem appropriate, including but not limited to cross-selling, promotion/conduct of marketing and direct marketing activities, research, providing advice or information covering products or services which the Companies believe may be of interest to me, to effectively administer or manage my account, enhance customer services, or to communicate with me for any purpose. The words collect and process are hereby understood to include any operation or any set of operations performed upon personal information including, but not limited to, the collection, recording, organization, storage, updating or modification, retrieval, consultation, use, consolidation, blocking, erasure or destruction of data.',
	p13:
		'Please make payments only to authorized Bank employees. Sales agents and/or referrers are not allowed to collect any fees of whatever nature on behalf of the Bank. Any payments made to individuals/entities not authorized by the Bank will not be binding on the Bank.',
};
