export const Nationality = [
	{ label: 'Afghan', value: 'afghan' },
	{ label: 'Albanian', value: 'albanian' },
	{ label: 'Algerian', value: 'algerian' },
	{ label: 'American', value: 'american' },
	{ label: 'Andorran', value: 'andorran' },
	{ label: 'Angolan', value: 'angolan' },
	{ label: 'Antiguans', value: 'antiguans' },
	{ label: 'Argentinean', value: 'argentinean' },
	{ label: 'Armenian', value: 'armenian' },
	{ label: 'Australian', value: 'australian' },
	{ label: 'Austrian', value: 'austrain' },
	{ label: 'Azerbaijani', value: 'azerbaijani' },
	{ label: 'Bahamian', value: 'bahamian' },
	{ label: 'Bahraini', value: 'bahraini' },
	{ label: 'Bangladeshi', value: 'bangladeshi' },
	{ label: 'Barbadian', value: 'barbadian' },
	{ label: 'Barbudans', value: 'barbudans' },
	{ label: 'Batswana', value: 'batswana' },
	{ label: 'Belarusian', value: 'belarusian' },
	{ label: 'Belgian', value: 'belgian' },
	{ label: 'Belizean', value: 'belizean' },
	{ label: 'Beninese', value: 'beninese' },
	{ label: 'Bhutanese', value: 'bhutanese' },
	{ label: 'Bolivian', value: 'bolivian' },
	{ label: 'Bosnian', value: 'bosnian' },
	{ label: 'Brazilian', value: 'brazilian' },
	{ label: 'British', value: 'british' },
	{ label: 'Bruneian', value: 'bruneian' },
	{ label: 'Bulgarian', value: 'bulgarian' },
	{ label: 'Burkinabe', value: 'burkinabe' },
	{ label: 'Burmese', value: 'burmese' },
	{ label: 'Burundian', value: 'burundian' },
	{ label: 'Cambodian', value: 'cambodian' },
	{ label: 'Cameroonian', value: 'cameroonian' },
	{ label: 'Canadian', value: 'canadian' },
	{ label: 'Cape Verdean', value: 'capeVerdean' },
	{ label: 'Central African', value: 'centralAfrican' },
	{ label: 'Chadian', value: 'chadian' },
	{ label: 'Chilean', value: 'chilean' },
	{ label: 'Chinese', value: 'chinese' },
	{ label: 'Colombian', value: 'colombian' },
	{ label: 'Comoran', value: 'comoran' },
	{ label: 'Congolese', value: 'congolese' },
	{ label: 'Costa Rican', value: 'costaRican' },
	{ label: 'Croatian', value: 'croatian' },
	{ label: 'Cuban', value: 'cuban' },
	{ label: 'Cypriot', value: 'cypriot' },
	{ label: 'Czech', value: 'czech' },
	{ label: 'Danish', value: 'danish' },
	{ label: 'Djibouti', value: 'djibouti' },
	{ label: 'Dominican', value: 'dominican' },
	{ label: 'Dutch', value: 'dutch' },
	{ label: 'East Timorese', value: 'eastTimorese' },
	{ label: 'Ecuadorean', value: 'ecuadorean' },
	{ label: 'Egyptian', value: 'egyptian' },
	{ label: 'Emirian', value: 'emirian' },
	{ label: 'Equatorial Guinean', value: 'equatorialGuinean' },
	{ label: 'Eritrean', value: 'eritrean' },
	{ label: 'Estonian', value: 'estonian' },
	{ label: 'Ethiopian', value: 'ethiopian' },
	{ label: 'Fijian', value: 'fijian' },
	{ label: 'Filipino', value: 'filipino' },
	{ label: 'Finnish', value: 'finnish' },
	{ label: 'French', value: 'french' },
	{ label: 'Gabonese', value: 'gabonese' },
	{ label: 'Gambian', value: 'gambian' },
	{ label: 'Georgian', value: 'georgian' },
	{ label: 'German', value: 'german' },
	{ label: 'Ghanaian', value: 'ghanaian' },
	{ label: 'Greek', value: 'greek' },
	{ label: 'Grenadian', value: 'grenadian' },
	{ label: 'Guatemalan', value: 'guatemalan' },
	{ label: 'Guinea-Bissauan', value: 'guinea-Bissauan' },
	{ label: 'Guinean', value: 'guinean' },
	{ label: 'Guyanese', value: 'guyanese' },
	{ label: 'Haitian', value: 'haitian' },
	{ label: 'Herzegovinian', value: 'herzegovinian' },
	{ label: 'Honduran', value: 'honduran' },
	{ label: 'Hungarian', value: 'hungarian' },
	{ label: 'I-Kiribati', value: 'i-Kiribati' },
	{ label: 'Icelander', value: 'icelander' },
	{ label: 'Indian', value: 'indian' },
	{ label: 'Indonesian', value: 'indonesian' },
	{ label: 'Iranian', value: 'iranian' },
	{ label: 'Iraqi', value: 'iraqi' },
	{ label: 'Irish', value: 'israeli' },
	{ label: 'Italian', value: 'italian' },
	{ label: 'Ivorian', value: 'ivorian' },
	{ label: 'Jamaican', value: 'jamaican' },
	{ label: 'Japanese', value: 'japanese' },
	{ label: 'Jordanian', value: 'Jordanian' },
	{ label: 'Kazakhstani', value: 'kazakhstani' },
	{ label: 'Kenyan', value: 'kenyan' },
	{ label: 'Kittian and Nevisian', value: 'kittianAndnevisian' },
	{ label: 'Kuwaiti', value: 'kuwaiti' },
	{ label: 'Kyrgyz', value: 'kyrgyz' },
	{ label: 'Laotian', value: 'laotian' },
	{ label: 'Latvian', value: 'Latvian' },
	{ label: 'Lebanese', value: 'Lebanese' },
	{ label: 'Liberian', value: 'Liberian' },
	{ label: 'Libyan', value: 'Libyan' },
	{ label: 'Liechtensteiner', value: 'Liechtensteiner' },
	{ label: 'Lithuanian', value: 'Lithuanian' },
	{ label: 'Luxembourger', value: 'Luxembourger' },
	{ label: 'Macedonian', value: 'Macedonian' },
	{ label: 'Malagasy', value: 'Malagasy' },
	{ label: 'Malawian', value: 'Malawian' },
	{ label: 'Malaysian', value: 'Malaysian' },
	{ label: 'Maldivian', value: 'Maldivian' },
	{ label: 'Malian', value: 'Malian' },
	{ label: 'Maltese', value: 'Maltese' },
	{ label: 'Marshallese', value: 'Marshallese' },
	{ label: 'Mauritanian', value: 'Mauritanian' },
	{ label: 'Mauritian', value: 'Mauritian' },
	{ label: 'Micronesian', value: 'Micronesian' },
	{ label: 'Moldovan', value: 'Moldovan' },
	{ label: 'Monacan', value: 'Monacan' },
	{ label: 'Mongolian', value: 'Mongolian' },
	{ label: 'Moroccan', value: 'Moroccan' },
	{ label: 'Mosotho', value: 'Mosotho' },
	{ label: 'Motswana', value: 'Motswana' },
	{ label: 'Mozambican', value: 'Mozambican' },
	{ label: 'Namibian', value: 'Namibian' },
	{ label: 'Nauruan', value: 'Nauruan' },
	{ label: 'Nepalese', value: 'Nepalese' },
	{ label: 'New Zealander', value: 'NewZealander' },
	{ label: 'Ni-Vanuatu', value: 'Ni-Vanuatu' },
	{ label: 'Nicaraguan', value: 'Nicaraguan' },
	{ label: 'Nigerian', value: 'Nigerian' },
	{ label: 'Nigerien', value: 'Nigerien' },
	{ label: 'North Korean', value: 'NorthKorean' },
	{ label: 'Northern Irish', value: 'NorthernIrish' },
	{ label: 'Norwegian', value: 'Norwegian' },
	{ label: 'Omani', value: 'Omani' },
	{ label: 'Pakistani', value: 'Pakistani' },

	{ label: 'Palauan', value: 'Palauan' },
	{ label: 'Panamanian', value: 'Panamanian' },
	{ label: 'Papua New Guinean', value: 'PapuaNewGuinean' },
	{ label: 'Paraguayan', value: 'Paraguayan' },
	{ label: 'Peruvian', value: 'Peruvian' },
	{ label: 'Philippines', value: 'Philippines' },
	{ label: 'Polish', value: 'Polish' },
	{ label: 'Portuguese', value: 'Portuguese' },
	{ label: 'Qatari', value: 'Qatari' },
	{ label: 'Romanian', value: 'Romanian' },
	{ label: 'Russian', value: 'Russian' },
	{ label: 'Rwandan', value: 'Rwandan' },
	{ label: 'Saint Lucian', value: 'SaintLucian' },
	{ label: 'Salvadoran', value: 'Salvadoran' },
	{ label: 'Samoan', value: 'Samoan' },
	{ label: 'San Marinese', value: 'SanMarinese' },
	{ label: 'Sao Tomean', value: 'SaoTomean' },
	{ label: 'Saudi', value: 'Saudi' },
	{ label: 'Scottish', value: 'Scottish' },
	{ label: 'Senegalese', value: 'Senegalese' },
	{ label: 'Serbian', value: 'Serbian' },
	{ label: 'Seychellois', value: 'Seychellois' },
	{ label: 'Sierra Leonean', value: 'SierraLeonean' },
	{ label: 'Singaporean', value: 'Singaporean' },
	{ label: 'Slovakian', value: 'Slovakian' },
	{ label: 'Slovenian', value: 'Slovenian' },
	{ label: 'Solomon Islander', value: 'SolomonIslander' },
	{ label: 'Somali', value: 'Somali' },
	{ label: 'South African', value: 'SouthAfrican' },
	{ label: 'South Korean', value: 'SouthKorean' },
	{ label: 'Spanish', value: 'Spanish' },
	{ label: 'Sri Lankan', value: 'SriLankan' },
	{ label: 'Sudanese', value: 'Sudanese' },
	{ label: 'Surinamer', value: 'Surinamer' },
	{ label: 'Swazi', value: 'Swazi' },
	{ label: 'Swedish', value: 'Swiss' },
	{ label: 'Syrian', value: 'Syrian' },
	{ label: 'Taiwanese', value: 'Taiwanese' },
	{ label: 'Tajik', value: 'Tajik' },
	{ label: 'Tanzanian', value: 'Tanzanian' },
	{ label: 'Thai', value: 'Thai' },
	{ label: 'Togolese', value: 'Togolese' },
	{ label: 'Tongan', value: 'Tongan' },
	{ label: 'Trinidadian or Tobagonian', value: 'TrinidadianOrTobagonian' },
	{ label: 'Tunisian', value: 'Tunisian' },
	{ label: 'Turkish', value: 'Turkish' },
	{ label: 'Tuvaluan', value: 'Tuvaluan' },
	{ label: 'Ugandan', value: 'Ugandan' },
	{ label: 'Ukrainian', value: 'Ukrainian' },
	{ label: 'Uruguayan', value: 'Uruguayan' },
	{ label: 'Uzbekistani', value: 'Uzbekistani' },
	{ label: 'Venezuelan', value: 'Venezuelan' },
	{ label: 'Vietnamese', value: 'Vietnamese' },
	{ label: 'Welsh', value: 'Welsh' },
	{ label: 'Yemenite', value: 'Yemenite' },
	{ label: 'Zambian', value: 'Zambian' },
	{ label: 'Zimbabwean', value: 'Zimbabwean' },
];
