// SIGN UP
export const REQUEST_SIGNUP = '[AUTH] REQUEST SIGNUP';
export const REQUEST_SIGNUP_SUCCESS = '[AUTH] REQUEST SIGNUP SUCCESS';
export const REQUEST_SIGNUP_FAIL = '[AUTH] REQUEST SIGNUP FAIL';

//VERIFY EMAIL
export const REQUEST_VERIFY_EMAIL = '[VERIFY] REQUEST EMAIL VERIFICATION';
export const REQUEST_VERIFY_EMAIL_SUCCESS =
	'[VERIFY] REQUEST EMAIL VERIFICATION SUCCESS';
export const REQUEST_VERIFY_EMAIL_FAIL =
	'[VERIFY] REQUEST EMAIL VERIFICATION FAIL';

// RESEND EMAIL CODE
export const RESEND_EMAIL_CODE = '[RESEND] EMAIL CODE';
export const RESEND_EMAIL_CODE_SUCCESS = '[RESEND] EMAIL CODE SUCCESS';
export const RESEND_EMAIL_CODE_FAIL = '[RESEND] EMAIL CODE FAIL';

// VERIFY PHONE
export const REQUEST_VERIFY_PHONE = '[VERIFY] REQUEST PHONE VERIFICATION';
export const REQUEST_VERIFY_PHONE_SUCCESS =
	'[VERIFY] REQUEST PHONE VERIFICATION SUCCESS';
export const REQUEST_VERIFY_PHONE_FAIL =
	'[VERIFY] REQUEST PHONE VERIFICATION FAIL';

// RESEND PHONE CODE
export const RESEND_PHONE_CODE = '[RESEND] PHONE CODE';
export const RESEND_PHONE_CODE_SUCCESS = '[RESEND] PHONE CODE SUCCESS';
export const RESEND_PHONE_CODE_FAIL = '[RESEND] PHONE CODE FAIL';

// CHANGE PHONE
export const CHANGE_PHONE = '[CHANGE] PHONE';
export const CHANGE_PHONE_SUCCESS = '[CHANGE] PHONE SUCCESS';
export const CHANGE_PHONE_FAIL = '[CHANGE] PHONE FAIL';

// VERIFY MFA
export const REQUEST_VERIFY_MFA = '[VERIFY] REQUEST MFA VERIFICATION';
export const REQUEST_VERIFY_MFA_SUCCESS =
	'[VERIFY] REQUEST MFA VERIFICATION SUCCESS';
export const REQUEST_VERIFY_MFA_FAIL = '[VERIFY] REQUEST MFA VERIFICATION FAIL';

// RESEND MFA
export const RESEND_MFA_CODE = '[RESEND] MFA CODE';
export const RESEND_MFA_CODE_SUCCESS = '[RESEND] MFA CODE SUCCESS';
export const RESEND_MFA_CODE_FAIL = '[RESEND] MFA CODE FAIL';

//LOG OUT
export const REQUEST_LOGOUT = '[AUTH] REQUEST LOGOUT';
export const REQUEST_LOGOUT_SUCCESS = '[AUTH] REQUEST LOGOUT SUCCESS';
export const REQUEST_LOGOUT_FAIL = '[AUTH] REQUEST LOGOUT FAIL';

//LOG IN
export const REQUEST_LOGIN = '[AUTH] REQUEST LOGIN';
export const REQUEST_LOGIN_SUCCESS = '[AUTH] REQUEST LOGIN SUCCESS';
export const REQUEST_LOGIN_FAIL = '[AUTH] REQUEST LOGIN FAIL';

// FORGOT PASSWORD
export const REQUEST_FORGOT_PASSWORD = '[FORGOT] SEND FORGOT';
export const REQUEST_FORGOT_PASSWORD_SUCCESS = '[FORGOT] SEND FORGOT SUCCESS';
export const REQUEST_FORGOT_PASSWORD_FAIL = '[FORGOT] SEND FORGOT FAIL';

// CHANGE PASSWORD REQUEST
export const CHANGE_PASSWORD_REQUEST = '[CHANGE] PASSWORD REQUEST';
export const CHANGE_PASSWORD_REQUEST_SUCCESS =
	'[CHANGE] PASSWORD REQUEST SUCCESS';
export const CHANGE_PASSWORD_REQUEST_FAIL = '[CHANGE] PASSWORD REQUEST FAIL';

// SIGN OUT
export const REQUEST_GLOBAL_SIGNOUT = '[AUTH] REQUEST GLOBAL SIGN OUT';
export const REQUEST_GLOBAL_SIGNOUT_SUCCESS =
	'[AUTH] REQUEST GLOBAL SIGN OUT SUCCESS';
export const REQUEST_GLOBAL_SIGNOUT_FAIL =
	'[AUTH] REQUEST GLOBAL SIGN OUT FAIL';

// REFRESH SESSION
export const REQUEST_REFRESH_SESSION = '[AUTH] REQUEST REFRESH SESSION';
export const REQUEST_REFRESH_SESSION_SUCCESS =
	'[AUTH] REQUEST REFRESH SESSION SUCCESS';
export const REQUEST_REFRESH_SESSION_FAIL =
	'[AUTH] REQUEST REFRESH SESSION FAIL';
