// PROFILE MODE
export const UPDATE_UI = '[UI] UPDATE UI';
export const UPDATE_UI_SUCCESS = '[UI] UPDATE UI SUCCESS';
export const UPDATE_UI_FAIL = '[UI] UPDATE UI FAIL';

// GLOBAL MESSAGE
export const ADD_GLOBAL_MESSAGE = '[UI] ADD GLOBAL MESSAGE';
export const REMOVE_GLOBAL_MESSAGE = '[UI] REMOVE GLOBAL MESSAGE';

//ERROR MESSAGE FOR FORMS
export const ADD_ERROR_MESSAGE = '[UI] ADD ERROR MESSAGE';
export const REMOVE_ERROR_MESSAGE = '[UI] REMOVE ERROR MESSAGE';

// GLOBAL LOADER
export const ADD_GLOBAL_LOADER = '[UI] ADD GLOBAL LOADER';
export const REMOVE_GLOBAL_LOADER = '[UI] REMOVE GLOBAL LOADER';
