// USER PASSWORD UPDATE
export const USER_PASSWORD_UPDATE = '[USER] PASSWORD UPDATE';
export const USER_PASSWORD_UPDATE_SUCCESS = '[USER] PASSWORD UPDATE SUCCESS';
export const USER_PASSWORD_UPDATE_FAIL = '[USER] PASSWORD UPDATE FAIL';

// GET USER INFO
export const GET_USER_INFO = '[USER] GET INFO';
export const GET_USER_INFO_SUCCESS = '[USER] GET INFO SUCCESS';
export const GET_USER_INFO_FAIL = '[USER] GET INFO FAIL';

// GET USER DEVICE
export const GET_USER_DEVICE = '[USER] GET USER DEVICE';
export const GET_USER_DEVICE_SUCCESS = '[USER] GET USER DEVICE SUCCESS';
export const GET_USER_DEVICE_FAIL = '[USER] GET USER DEVICE FAIL';

// FORGOT USER DEVICE
export const FORGOT_USER_DEVICE = '[USER] FORGOT DEVICE';
export const FORGOT_USER_DEVICE_SUCCESS = '[USER] FORGOT DEVICE SUCCESS';
export const FORGOT_USER_DEVICE_FAIL = '[USER] FORGOT DEVICE FAIL';

// FORGOT ALL USER DEVICES
export const FORGOT_USER_ALL_DEVICE = '[USER] FORGOT USER ALL DEVICE';
export const FORGOT_USER_ALL_DEVICE_SUCCESS =
	'[USER] FORGOT ALL DEVICE SUCCESS';
export const FORGOT_USER_ALL_DEVICE_FAIl = '[USER] FORGOT ALL DEVICE FAIL';
